"""
Code generation for builder-created capabilities.

Generates clean, production-quality Python source code, test stubs, and YAML
configuration for capabilities created through the builder.

Uses string templates only — no external template dependencies.
"""

from typing import Any, Dict
from datetime import datetime
import json


def generate_capability_code(session: Any) -> str:
    """Generate Python source code for a capability.

    Creates a complete, deployable Capability class with:
    - Intent patterns for routing
    - Worker slot configuration
    - Prompt template with Template Method slots
    - Output schema validation
    - Few-shot examples

    Args:
        session: BuilderSession with completed capability definition.

    Returns:
        Python source code string (importable and runnable).
    """
    # Convert intent patterns to Python list literal
    intents_str = _python_list_literal(session.intent_patterns)

    # Convert worker slots dict
    worker_slots_str = _python_dict_literal(session.worker_slots)

    # Convert examples to Python list of dicts
    examples_str = _python_list_literal(session.examples)

    # Convert output schema to Python dict
    schema_str = _python_dict_literal(session.output_schema or {})

    # Convert validation rules to list
    rules_str = _python_list_literal(session.validation_rules)

    # Escape the prompt template for Python string
    prompt_escaped = _escape_string(session.prompt_template or "")

    # Generate class name from capability name
    class_name = _to_class_name(session.name or "Capability")

    # Build the source code
    code = f'''"""
{session.description or "Capability generated by Agentend builder."}

Generated: {datetime.utcnow().isoformat()}
Builder Session: {session.session_id}
"""

from typing import Any, Dict, Optional
from dataclasses import dataclass, field
import json
import logging

logger = logging.getLogger(__name__)


@dataclass
class {class_name}Context:
    """Context for {class_name} execution."""
    input: str
    """The input text to process."""
    metadata: Dict[str, Any] = field(default_factory=dict)
    """Additional metadata for context."""


class {class_name}:
    """
    {session.description or "Capability created via builder."}

    This capability was generated through the Agentend conversational builder.
    It accepts natural language or structured input and produces classified,
    extracted, or generated output according to the prompt template.
    """

    # Capability metadata
    name: str = "{session.name or class_name.lower()}"
    description: str = "{_escape_docstring(session.description or '')}"

    # Intent routing
    intents: list = {intents_str}

    # Worker slot configuration
    worker_slots: dict = {worker_slots_str}

    # Output schema for validation
    output_schema: dict = {schema_str}

    # Validation rules
    validation_rules: list = {rules_str}

    # Few-shot examples for in-context learning
    examples: list = {examples_str}

    # Prompt template with Template Method slots
    prompt_template: str = """{prompt_escaped}"""

    def __init__(self):
        """Initialize the capability."""
        self.logger = logging.getLogger(self.name)

    async def execute(self, context: {class_name}Context, **kwargs: Any) -> Dict[str, Any]:
        """
        Execute the capability.

        Args:
            context: Execution context with input and metadata.
            **kwargs: Additional arguments (e.g., worker overrides).

        Returns:
            Dict with capability output conforming to output_schema.
        """
        try:
            # Render the prompt template with context
            prompt = self._render_prompt(context)

            # Call the appropriate worker (determined by worker_slots)
            # In production, this would dispatch to a worker pool
            # For now, return a structured placeholder
            result = await self._call_worker(prompt, context, **kwargs)

            # Validate the result against the schema
            validated = self._validate_output(result)

            return {{
                "success": True,
                "output": validated,
                "session": context.metadata.get("session_id"),
            }}

        except Exception as e:
            self.logger.error(f"Execution failed: {{e}}", exc_info=True)
            return {{
                "success": False,
                "error": str(e),
                "session": context.metadata.get("session_id"),
            }}

    def _render_prompt(self, context: {class_name}Context) -> str:
        """
        Render the prompt template with Template Method slots.

        Args:
            context: Execution context.

        Returns:
            Rendered prompt string.
        """
        prompt = self.prompt_template

        # Replace Template Method slots
        # {{ context }} -> user input
        prompt = prompt.replace("{{ context }}", context.input)

        # {{ validation_rules }} -> formatted rules
        rules_text = "\\n".join(f"- {{r}}" for r in self.validation_rules)
        prompt = prompt.replace("{{ validation_rules }}", rules_text)

        # {{ examples }} -> formatted few-shot examples
        examples_text = self._format_examples()
        prompt = prompt.replace("{{ examples }}", examples_text)

        return prompt

    def _format_examples(self) -> str:
        """Format few-shot examples for the prompt.

        Returns:
            Formatted examples string.
        """
        if not self.examples:
            return "(No examples provided)"

        formatted = []
        for i, example in enumerate(self.examples, 1):
            inp = example.get("input", "")
            out = example.get("output", "")
            formatted.append(f"Example {{i}}:\\nInput: {{inp}}\\nOutput: {{out}}")

        return "\\n\\n".join(formatted)

    async def _call_worker(
        self, prompt: str, context: {class_name}Context, **kwargs: Any
    ) -> Dict[str, Any]:
        """
        Call the appropriate worker to process the prompt.

        In a real deployment, this would dispatch to the worker pool
        configured in fleet.yaml. For testing, this is a placeholder.

        Args:
            prompt: Rendered prompt string.
            context: Execution context.
            **kwargs: Worker overrides (e.g., model, temperature).

        Returns:
            Worker response as dict.
        """
        # TODO: Integrate with actual worker dispatch
        # For now, return a placeholder response
        self.logger.debug(f"Would call worker with prompt ({{len(prompt)}} chars)")

        return {{
            "status": "placeholder",
            "message": "Worker integration needed for actual execution",
            "prompt_length": len(prompt),
        }}

    def _validate_output(self, output: Any) -> Dict[str, Any]:
        """
        Validate output against the schema.

        Args:
            output: Output from worker.

        Returns:
            Validated output dict.

        Raises:
            ValueError: If validation fails.
        """
        if not isinstance(output, dict):
            if isinstance(output, str):
                try:
                    output = json.loads(output)
                except json.JSONDecodeError as e:
                    self.logger.warning(f"Failed to parse JSON output: {{e}}")
                    output = {{"raw": output}}

        # Check required fields from schema
        schema = self.output_schema
        required = schema.get("required", [])
        properties = schema.get("properties", {{}})

        for field_name in required:
            if field_name not in output:
                self.logger.warning(f"Missing required field: {{field_name}}")

        # Return validated output
        return output


# Export for registration
__all__ = ["{class_name}", "{class_name}Context"]
'''

    return code


def generate_test_code(session: Any) -> str:
    """Generate pytest test stubs for a capability.

    Args:
        session: BuilderSession with completed capability definition.

    Returns:
        Python test code string.
    """
    class_name = _to_class_name(session.name or "Capability")
    module_name = session.name or "capability"

    code = f'''"""
Tests for {class_name} capability.

Generated by Agentend builder.
"""

import pytest
from {module_name} import {class_name}, {class_name}Context


@pytest.fixture
def capability():
    """Fixture providing a {class_name} instance."""
    return {class_name}()


@pytest.mark.asyncio
async def test_execute_basic(capability):
    """Test basic capability execution."""
    context = {class_name}Context(
        input="Test input",
        metadata={{"session_id": "test-session"}},
    )

    result = await capability.execute(context)

    assert result["success"] in (True, False)
    assert "session" in result


@pytest.mark.asyncio
@pytest.mark.parametrize("test_input,expected_in_output", [
'''

    # Add examples as test cases
    for i, example in enumerate(session.examples[:3]):
        input_str = example.get("input", "").replace('"', '\\"')
        code += f'''    ("{input_str}", "output"),\n'''

    code += f'''])
async def test_execute_with_examples(capability, test_input, expected_in_output):
    """Test capability with few-shot examples."""
    context = {class_name}Context(
        input=test_input,
        metadata={{"session_id": "test-example"}},
    )

    result = await capability.execute(context)

    assert "output" in result or "error" in result


def test_schema_validation(capability):
    """Test that output schema is properly defined."""
    assert capability.output_schema is not None
    assert "properties" in capability.output_schema
    assert capability.output_schema.get("type") == "object"


def test_intent_patterns(capability):
    """Test that intent patterns are configured."""
    assert len(capability.intents) > 0
    assert all(isinstance(intent, str) for intent in capability.intents)


def test_prompt_template(capability):
    """Test that prompt template is defined."""
    assert capability.prompt_template is not None
    assert len(capability.prompt_template) > 0
    assert "{{" in capability.prompt_template  # Has template slots


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
'''

    return code


def generate_fleet_config(session: Any) -> str:
    """Generate fleet.yaml additions for the capability.

    Args:
        session: BuilderSession with completed capability definition.

    Returns:
        YAML configuration string.
    """
    capability_name = session.name or "capability"

    # Build worker slot overrides section
    overrides = ""
    if session.worker_slots:
        for slot, model in session.worker_slots.items():
            overrides += f"""
  {slot}:
    model: {model}
"""

    yaml = f"""# Generated capability registration for: {capability_name}
# Created: {datetime.utcnow().isoformat()}
# Builder Session: {session.session_id}

capabilities:
  {capability_name}:
    enabled: true
    description: "{session.description or ''}"
    intent_patterns:
"""

    # Add intent patterns
    for pattern in session.intent_patterns:
        yaml += f'      - "{pattern}"\n'

    yaml += "\n"

    # Add worker slot overrides if present
    if overrides:
        yaml += f"""    worker_overrides:{overrides}"""

    yaml += f"""
    output_schema:
      type: object
      required:
"""

    # Add required fields
    if session.output_schema and "required" in session.output_schema:
        for field in session.output_schema["required"]:
            yaml += f'        - "{field}"\n'

    yaml += """
# NOTE: To integrate this configuration:
# 1. Add the above YAML to your fleet.yaml under the 'capabilities' section
# 2. Reload or restart Agentend to register the new capability
# 3. The capability will become available for intent routing
"""

    return yaml


def _python_list_literal(items: list) -> str:
    """Convert Python list to a literal string representation.

    Args:
        items: List to convert.

    Returns:
        String like "[1, 2, 3]".
    """
    if not items:
        return "[]"

    # Handle list of dicts vs strings
    if items and isinstance(items[0], dict):
        dicts_str = ",\n        ".join(json.dumps(item) for item in items)
        return f"[\n        {dicts_str}\n    ]"
    else:
        items_str = ", ".join(json.dumps(item) for item in items)
        return f"[{items_str}]"


def _python_dict_literal(data: dict) -> str:
    """Convert Python dict to a literal string representation.

    Args:
        data: Dict to convert.

    Returns:
        String like "{'key': 'value'}".
    """
    if not data:
        return "{}"

    return json.dumps(data, indent=8)


def _escape_string(s: str) -> str:
    """Escape a string for Python source code.

    Args:
        s: String to escape.

    Returns:
        Escaped string.
    """
    return s.replace('"', '\\"').replace("\n", "\\n")


def _escape_docstring(s: str) -> str:
    """Escape a string for use in a Python docstring.

    Args:
        s: String to escape.

    Returns:
        Escaped string.
    """
    return s.replace('"""', '\\"""').replace("\n", "\\n")


def _to_class_name(name: str) -> str:
    """Convert snake_case name to PascalCase class name.

    Args:
        name: Name to convert (e.g., 'ticket_classifier').

    Returns:
        Class name (e.g., 'TicketClassifier').
    """
    parts = name.split("_")
    return "".join(part.capitalize() for part in parts)


__all__ = [
    "generate_capability_code",
    "generate_test_code",
    "generate_fleet_config",
]
